apiVersion: apps/v1
kind: Deployment
metadata: 
  name: apache2
  labels:
    app: apache2
spec:
  replicas: 2
  selector: 
   matchLabels:
     app: apache2
  template:
    metadata: 
       name: my-pod
       labels:
         app: apache2
    spec:
      containers:
         - name: apache-cont
           image: httpd
           ports:
             - containerPort: 8080