apiVersion: apps/v1
kind: Deployment
metadata: 
  name: customWebsite
  labels:
    app: customWebsite
spec:
  replicas: 2
  selector: 
   matchLabels:
     app: customWebsite
  template:
    metadata: 
       name: custom-pod
       labels:
         app: customWebsite
    spec:
      containers:
         - name: custom-cont
           image: saikumar97058/custom-apache2
           ports:
             - containerPort: 8080