apiVersion: apps/v1
kind: Deployment
metadata: 
  name: customwebsite
  labels:
    app: customwebsite
spec:
  replicas: 2
  selector: 
   matchLabels:
     app: customwebsite
  template:
    metadata: 
       name: custom-pod
       labels:
         app: customwebsite
    spec:
      containers:
         - name: custom-cont
           image: saikumar97058/custom-apache2:v1
           ports:
             - containerPort: 8080