apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deployment
  labels:
    app: my-deployment
spec:
  replicas: 2
  selector: 
   matchLabels:
     app: my-app
  template:
    metadata: 
       name: my-pod
       labels:
         app: my-app
    spec:
      containers:
         - name: my-cont
           image: httpd
           ports:
             containerPort: 8080